### ISSUE TITLE
In waveform_tutorial, please don't start with finite radius waveforms.

### ISSUE THREAD

**Issue by markscheel** [sxs-collaboration/catalog_tools#4]
Most people should never use finite radius waveforms.  In the tutorial, it would be better to start with COM-corrected extrapolated waveforms, and then later have a section that says something like "If you really really need finite radius waveforms (say for debugging the extrapolated waveforms), here's what to do." and then talks about how to get finite radius waveforms.

**Comment by 10220** [comment]
PR #6
