### ISSUE TITLE
sxs.zenodo.download module not found

### ISSUE THREAD

**Issue by tandradew** [sxs-collaboration/catalog_tools#8]
The Jupyter notebook Examples/sxs_catalog_download_example.ipynb calls the module sxs.zenodo.download but this no longer exists in the current version of the API. Try using sxs.load() instead, see 'Usage' section of the documentation in https://github.com/sxs-collaboration/sxs

**Comment by geoffrey4444** [comment]
Thanks for catching this! When I wrote the original catalog_tools code, I didn’t include any automatically-run tests, so I never noticed when the sxs library changed.

We'll discuss at our weekly meeting a plan to update these notebooks. If you don't hear back from me by the end of next week, please don't hesitate to ping me :)

**Comment by tandradew** [comment]
great, thank you, Geoffrey! Leo and Mike pointed me to alternative Python
resources to get started with the sxs catalogue, I think that's all I need
for now.

best,
Tomas
